--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/antbag-dev/JoinCount
build-by-default: true
branches:
- main
projects: 
  JoinCount:
    path: ""
    libs:
    - src: fernanACM/CortexPE/DiscordWebhookAPI
      version: ^1.0.3
      branch: PM5
...
